### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by danthanhtrung** [nallaajay/Autonomous-Robot-Path-Finding-Application#1]
I downloaded it but it doesn't work
Can you commit Full Source I refer to my project

**Comment by nallaajay** [comment]
Hope you have read the readme file, all you need to do is: 

"To run the program, the .NET Framework is required. Extract the executable and setup from the Autonomous_Robot_Path_Finding_Application.zip folder to run the application. The necessary runtime files (.dll, .runtimeconfig etc.) are also included in the folder."

Just download the Autonomous_Robot_Path_Finding_Application.zip file, extract the files (Unzip the folder), in that folder there will be "setup" (application file), just double click on that file. It will ask you for permission and once you give that the application will run. 

Make sure you have already installed the visual studio code with .NET Framework. 

The full source code is already committed. 

Hope this resolves your issue. 

Thank you
